name: Deploy Storybook to GitHub Pages

# 이 워크플로우는 build-all-pr.yml로 대체되었습니다
# main 브랜치에서만 실행하도록 제한
on:
  push:
    branches: ['main']
  # pull_request는 build-all-pr.yml에서 처리

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지를 위한 설정
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json

      - name: Install workspace dependencies
        run: |
          # 전체 workspace 의존성 설치 (husky 스크립트 무시)
          npm ci --ignore-scripts

      - name: Verify workspace setup
        run: |
          echo "✅ Workspace dependencies installed successfully"
          echo "📦 Workspace packages:"
          ls -la packages/

      - name: Build Storybook
        run: |
          cd packages/ui
          npm run build-storybook
          echo "✅ Storybook built successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/ui/storybook-static'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # 환경 보호 규칙 우회를 위한 조건부 배포
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: https://storybook.bugi.co.kr
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy info
        run: |
          echo "✅ Storybook deployed successfully!"
          echo "🌐 Custom Domain: https://storybook.bugi.co.kr"
          echo "📁 Source directory: packages/ui/storybook-static"
          echo "📝 Commit: ${{ github.sha }}"
          echo ""
          echo "🔧 DNS 설정 필요:"
          echo "   CNAME 레코드: storybook.bugi.co.kr → [username].github.io"
